# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: openisms/openisms
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - "ghcr.io/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - static
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .ProjectName }}:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - static
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: ghcr.io/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/{{ .ProjectName }}:latest-amd64
      - ghcr.io/{{ .ProjectName }}:latest-arm64v8
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - static/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
